
# --- Database Connection ---
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/serenity_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
hibernate.connection.username=root
hibernate.connection.password=mysql
# --- Hibernate Dialect ---
hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Schema Management ---
# Options: validate | update | create | create-drop
hibernate.hbm2ddl.auto=update

# --- SQL Logging ---
hibernate.show_sql=true
hibernate.format_sql=true

# --- Connection Pool (C3P0) ---
hibernate.connection.pool_size=10

# --- Current Session Context ---
hibernate.current_session_context_class=thread
hibernate.cache.use_second_level_cache=true
hibernate.cache.region.factory_class=org.hibernate.cache.jcache.internal.JCacheRegionFactory
hibernate.javax.cache.uri=ehcache.xml
hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
